# Generated by Django 4.1.7 on 2023-03-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displayconf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidata',
            name='tags',
            field=models.JSONField(default=dict, max_length=200),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='data',
            field=models.JSONField(default=dict, max_length=500),
        ),
    ]
