# Generated by Django 4.1.7 on 2023-03-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displayconf', '0003_api_base_address_api_creation_date_api_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='base_address',
            field=models.URLField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='api',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
