# Generated by Django 4.1.7 on 2023-03-21 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('displayconf', '0004_alter_api_base_address_alter_api_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='api',
            name='format',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='api',
            name='name',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='params',
            field=models.JSONField(blank=True, default=list, max_length=100),
        ),
        migrations.AlterField(
            model_name='api',
            name='token',
            field=models.JSONField(blank=True, default=dict, max_length=100),
        ),
        migrations.AddField(
            model_name='apidata',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='displayconf.api'),
        ),
    ]
