# Generated by Django 4.1.7 on 2023-03-21 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('displayconf', '0005_apidata_delete_user_alter_api_format_alter_api_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiData',
        ),
    ]
