# Generated by Django 4.1.7 on 2023-03-21 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('displayconf', '0006_delete_apidata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(max_length=500)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='displayconf.api')),
            ],
        ),
    ]
